README.md
package.json

the default is 127.0.0.1, and does not allow oustide connections. With this change, we can

set hostname to 0.0.0.0

---

migration-params.json

use ganache addresses as founders

---

migrate-base.js
migrate-demo-test.js
migration-params.json
migration.json
package-lock.json
package.json

release 0.0.1-rc.12-v0

---

README.md
migrate-dao.js
migrate.js
migration-params.json
migration.json
package-lock.json
package.json

release 0.0.1-rc.12-v4

---

migrate-base.js
migrate-demo-test.js
package.json

Give all Ganache accounts GEN

---

README.md
migrate-dao.js
migrate-demo-test.js
migration-params.json
migration.json
package-lock.json
package.json

release 0.0.1-rc.14-v0

---

package-lock.json
package.json

Update arc-hives to rc-4

---

README.md
migrate-dao.js
migration-params.json
package-lock.json
package.json

Added DAOCreator support to the script.
Update Arc to v15 (no changes to the migration supported contracts were made).

Added DAOCreator support to the script.

---

migrate-dao.js

Fix tx logging

---

package-lock.json
package.json

fix #118
update the following packages : 
"tar": "^4.4.8",
"fstream": "^1.0.12"
"eslint": "^5.16.0",

fix packages vulnerability .

---

migration.json
package-lock.json
package.json

Fix corrupted ganache db in previous release.

release 0.0.1-rc.19-v5

---

migrate-dao.js
migrate.js
migration.json

This PR fixes a crash which may happen when the requesting a transaction returns null. Also it improves the adding founders method so that each round can now add 100 founders.

Improvement and bug fixes

---

prepare-release.sh

Fix errors in the prepare-release script that crept in when adding the provider for when verifying contracts that have constructor arguments.

fixPrepareRelease

---

migrate-dao.js
migrate-demo-test.js

Register DAO on Ganache DAORegistry

---

README.md

Improved deployment doc.

---

migrate-dao.js

add Schemes filed to migrate.dao output

---

migrate-dao.js

Fix custom schemes

---

README.md
daos-params/migration-params-block-explode.json
daos-params/migration-params-pepper4d.json
migrate-dao.js
migration-params.json
package-lock.json

Support the same scheme multiple times

---

migrate-dao.js

The diff looks like I did a lot, but all I did was wrap the block of code in `if (migrationParams.CustomSchemes) { ... }`.

Make CustomSchemes Optional

---

migrate-dao.js
migrate-demo-test.js
package-lock.json
package.json
sanitize.js

Closes: https://github.com/daostack/migration/issues/171

JSON Sanitizing

---

migrate-dao.js

Could you please publish a new NPM package with this change in it @ben-kaufman?

CustomScheme.Address Fix

---

migrate-dao.js

Add arcVersion and pretty print DAO json

---

.gitignore
README.md
migrate-dao.js
migrate.js

Save state of DAO deployment.

---

migrate-dao.js

Print parameters

---

migrate-dao.js

PR #230 had a bug which caused the `--restart` flag to stop working.

Fix restart flag

---

migrate-dao.js
migrate.js

WIP: New sendTx functionality

---

README.md
migrate-dao.js

Allow specifying Arc version in parameters file.

---

optimize-abis.js

Found this bug while trying to execute the optimize-abis.js script from within a node instance that was spawned by another project.
Please publish a new revision of the NPM package when merged @ben-kaufman :pray:

Abs Path Fix

---

migration.json
package-lock.json
package.json

release 0.0.1-rc.36-v5

---

package-lock.json
package.json

Update web3 and ganache

---

migration-params.json
migration.json
package-lock.json
package.json

release 0.0.1-rc.41-v4

---

README.md
migrate-dao.js

An example of this would be the "ActionMock" contract in Arc.

Support Non-ZOS StandAlone Contracts

---

migrate-demo-test.js
migration.json
package-lock.json
package.json

release 0.0.1-rc.41-v5

---

migrate-dao.js
migration.json
package-lock.json
package.json

Allow using avatar, daotoken, rep as deplotment params

---

migrate-dao.js
migrate.js
migration.json
package-lock.json
package.json

Change standalone contracts default admin on ganache.

release 0.1.1-rc.23-v4

---

migration-params.json
migration.json
package-lock.json
package.json

Adds CL4R to the demo dao for testing

release 0.0.1-rc.52-v1
